### ISSUE TITLE
HTML tags don't show up in completion

### ISSUE THREAD

**Issue by PranavSenthilnathan** [microsoft/vs-ng-language-service#10]
Currently when this extension is enabled, completion for html tags in the component.html files do not show up (only angular completions at the position show up). By default multiple completion providers should work seamlessly and provide the combination of all available completions but some internal implementations are causing this to not work in this case. We should consider making the HTML completion provider asynchronous, using the synchronous provider in our LSP implementation, or some other option to get this working.

![image](https://user-images.githubusercontent.com/12225508/89591120-422afd00-d7fe-11ea-8fee-47f29b3b5c78.png)

**Comment by John0King** [comment]
html highlight for single `.ts` file  seems not work neighter.
```ts
@Component({
    template: `  <a> </a> ` ,   intellisence  work, but not heighlight and  complete tag 
})
export class FooComponent implements OnInit {
   ngOnInit(): void {
  }
}
```

**Comment by vosonha89** [comment]
I also have problems, when try to enable services.
![image](https://user-images.githubusercontent.com/6813216/98960734-5e45e500-2537-11eb-8815-ddbe5e40cc12.png)
Error log here:
![image](https://user-images.githubusercontent.com/6813216/98960885-8897a280-2537-11eb-8f73-6f55794a1e7a.png)
