### ISSUE TITLE
Crash when opening TS file

### ISSUE THREAD

**Issue by elvince** [microsoft/vs-ng-language-service#13]
Hi,

I tried to installed this extension and it immediatly crash multiple times in vs 2019 16.7.4 and 16.7.3.

Plz find attached the activity log that is produced by the extension in "/log" mode

[ActivityLogDetailled.log](https://github.com/microsoft/vs-ng-language-service/files/5298316/ActivityLogDetailled.log)

I hope you can fix that.

**Comment by gcrev93** [comment]
Hey .. did the new version of the extension fix this issue?

**Comment by elvince** [comment]
Still the same issue.
It loads then a log of ntofication appears that this extension crashed

Thanks

**Comment by MariaSolOs** [comment]
@elvince Could you please try updating to the latest version of the extension and let us know if the issue persists?

**Comment by MariaSolOs** [comment]
Closing as we never heard back from the user.
