### ISSUE TITLE
Extension makes auto completion works only by Tab or Enter

### ISSUE THREAD

**Issue by ashrafsabrym** [microsoft/vs-ng-language-service#14]
Installing the extension makes the JavaScript/TypeScript editor acts as if the _Only use Tab or Enter to commit_ option in Visual Studio is set (In Options > Text Editor > JavaScript/TypeScript > Intellisense)
Selecting an element from auto complete list only works by pressing Tab or Enter.

**Comment by MariaSolOs** [comment]
@ashrafsabrym Thank you for submitting the issue! Could you please try downloading the latest version of the extension and let us know if the issue persists?

**Comment by MariaSolOs** [comment]
Closing as we never heard back from the user.
