### ISSUE TITLE
Cannot link .html template with .ts file

### ISSUE THREAD

**Issue by vosonha89** [microsoft/vs-ng-language-service#16]
![image](https://user-images.githubusercontent.com/6813216/104018765-f6391580-51ec-11eb-994c-ef8e4058fb6e.png)
![image](https://user-images.githubusercontent.com/6813216/104018787-ffc27d80-51ec-11eb-8e50-7df1f979bba8.png)
My visual studio 2019 already installed extension, but when I open .html template, my visual studio cannot link property from .ts file to make suggestion.
Any helps for this? Many thanks.

**Comment by MariaSolOs** [comment]
@vosonha89 Could you please try updating to the latest version of the extension and let us know if the issue persists?

**Comment by MariaSolOs** [comment]
Closing as we never heard back from the user.
