### ISSUE TITLE
Completions in projection buffers are not delegated to our language server

### ISSUE THREAD

**Issue by PranavSenthilnathan** [microsoft/vs-ng-language-service#20]
Completions inside projection buffers refers to the scenario of completion at the caret below:
```
<p aria-live="polite">Current count: <strong>{{ currentCo| }}</strong></p>
                                                         ^
```

This used to work previously but now it looks like the projection buffer is no longer treated as an angularTemplate content type so the editor/LSP doesn't invoke our completions.

The fix would have to somehow modify our content type or generally get editor/LSP to recognize our completion provider as suitable for the content type.

**Comment by MariaSolOs** [comment]
This is now fixed in VS 2022.
