### ISSUE TITLE
Migrate from IVsOutputWindow to IOutputChannelStore for writing to the output window

### ISSUE THREAD

**Issue by uniqueiniquity** [microsoft/vs-ng-language-service#23]
`IVsOutputWindow` requires us to acquire the main thread to write to the output window, whereas `IOutputChannelStore` is free-threaded (I think).

https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.rpccontracts.outputchannel.ioutputchannelstore?view=visualstudiosdk-2019

**Comment by MariaSolOs** [comment]
Closing this as we're not using a custom output pane anymore.
