### ISSUE TITLE
Angular Language Service Extension

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/vs-ng-language-service#25]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Angular-Language-Service-Extension/1376046)._

---
Angular Language Service Extension starts multiple times and somehow "eats" the RAM (in Visual Studio 2019 Community)

Info: Angular language server process ID: 11384
Info: Using typescript v3.9.7 from C:\USERS\USER\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_FFFF9429\EXTENSIONS\FMEMI0X1. FAX\node_modules\typescript\lib\tsserverlibrary.js
Info: Using @angular/language-service v10.0.4 from C:\USERS\USER\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_FFFF9429\EXTENSIONS\FMEMI0X1. FAX\node_modules\@angular\language-service\bundles\language-service.umd.js
Info: Log file: undefined
Warning: Using less efficient polling watcher. Set TSC_NONPOLLING_WATCHER to true.

---
#### Feedback Bot on 3/21/2021, 06:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MariaSolOs** [comment]
Closing as we never heard back from the user.
