### ISSUE TITLE
Angular language server extension loops continually when no config file present

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/vs-ng-language-service#28]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Angular-language-server-extension-loops-/1146147)._

---
[severity:I'm frustrated, but able to complete my work]
I noticed the Angular Language Server extension output errors in a continual loop. I cannot capture the full text but I am attaching screenshots. VS 2019 Version 16.7.0

---
#### Feedback Bot on 8/12/2020, 01:54 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Tina Schrepfer (VS) [MSFT] on 8/12/2020, 09:42 AM: 

<p>Thank you for your feedback.  Unfortunately, the screenshot clipped a bunch of text.  Can you please copy the content from Angular Language Service output window and attach it here?</p>
<p>We look forward to hearing from you.</p>
<p>Thanks,</p>
<p>Tina</p>

#### Tim on 8/12/2020, 11:00 PM: 

<p>Hi, as I mentioned it wasn't possible to copy the context from the output window because of the continual loop. In fact, when I did try, it actually made Notepad freeze (on the paste operation) presumably because the clipboard tried to contact the source window. The Angular Language Service output window would fill and then empty again. I have disabled the extension, but will re-enable  and see if I can get another screenshot.</p>

#### Tina Schrepfer (VS) [MSFT] on 8/13/2020, 11:52 AM: 

<p>Thanks Tim!  Is this behavior be reproduced consistently?  If so, can you share the exact repro steps?</p><p>Tina</p>

#### Feedback Bot on 8/26/2020, 06:11 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Tim on 9/4/2020, 01:48 AM: 

(private comment, text removed)
#### Tina Schrepfer (VS) [MSFT] on 9/4/2020, 09:15 AM: 

<p>Thanks Tim!  Instead of taking a screenshot of the output window, could you please copy and paste the content of the entire output window and attach it here?</p><p>Tina</p>

#### Tim on 9/4/2020, 09:48 AM: 

<p>Hi, I am sorry you don't understand this. It is not possible to copy and paste the contents of the output window. That is why I have used a screenshot. When I tried to copy and paste the text Notepad hung.</p><p>Tim</p>

#### Tina Schrepfer (VS) [MSFT] on 9/4/2020, 10:42 AM: 

<p>The output window is a just a text editor that's in read only mode.  You should be able to select all and then copy like any other editors.  Is that not working for you?  If it is, then that's a different issue.  What do you see when you right click on the output window?</p><p>Thanks,</p><p>Tina</p>

#### Tim on 9/4/2020, 00:04 PM: 

<p>It is the same issue. The text loops so the output window is always filling, cleared, and filling again. It does not stop to let you select text. And if you do, you can’t paste it, presumably because the clipboard api tries to contact the source window.</p><p>Tim</p>

#### Feedback Bot on 9/4/2020, 01:26 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### Tim solved on 9/4/2020, 00:03 PM, 0 votes: 

<p>Please delete</p>

**Comment by MariaSolOs** [comment]
Closing as the user never followed back here.
