### ISSUE TITLE
Error activating remote language server, Angular Language Service Extension

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/vs-ng-language-service#30]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-activating-remote-language-server/1410849)._

---
[severity:It's more difficult to complete my work]
When trying to work on an Angular file, the error in the attaced screenshot appeared. No special actions to reproduce.
Only note that previously I had received an AggregateException (log attached: 'ActivityLog.xml') some time after loading the solution. and opening the .ts file

---
#### null on 4/29/2021, 11:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by uniqueiniquity** [comment]
Angular Extension version 1.1, VS version 16.9.4.

**Comment by bitbau** [comment]
Getting the same error message on top of a *.component.html file when code completion (intellisense) tries to display its suggestions. It seems it has something to do with special unicode characters. In my case it was the 🔒-Sign. Angular Language Service doesn't seem to cope with that...

**Comment by MariaSolOs** [comment]
@bitbau Could you please try updating to the latest version of the extension and let us know if the issue persists?

**Comment by MariaSolOs** [comment]
Closing as we never heard back from the user.
