### ISSUE TITLE
No features available, no errors but no additional features

### ISSUE THREAD

**Issue by dylandhall** [microsoft/vs-ng-language-service#31]
I can see the language service initialising and running, and providing feedback when I modify files. However, no autocomplete or F12 functionality exists.

Angular 11
.Net framework 4.7.2
Visual studio 16.10.1

We use angular workspaces and have four angular projects within our solution.

One possible issue is we block typescript compile in the csproj file (and after a certain version we also had to record the files as `<None />` instead of `<TypeScriptCompile />` inclusions in the csproj file). We had issues with the version of typescript visual studio was using so we have angular build and webpack handle everything for us.

Is there any known issue with this configuration? Would love to get it working.

I can provide logs if needed.

**Comment by MariaSolOs** [comment]
@dylandhall Could you please try updating to the latest version of the extension and let us know if the issue persists?

**Comment by MariaSolOs** [comment]
Closing as we never heard back from the user.
