### ISSUE TITLE
Extension not available in Visual Studio 2022

### ISSUE THREAD

**Issue by kateract** [microsoft/vs-ng-language-service#34]
The Angular Language Service Extension is not available in the extension marketplace for Visual Studio 2022.  The 2022 version has some specific enhancements that make it easier to work with typescript and javascript projects thanks to the introduction of esproj files, and I'd like to be able to use this extension going forward in my mixed solutions.

**Comment by ssougnez** [comment]
Hello, any update on this?

**Comment by rfajkowski** [comment]
Any progress with implementing this for VS2022?

**Comment by zkat** [comment]
I don't have an exact timeline, but our team will be prioritizing this work for "soon". Feel free to subscribe to this issue for further updates.

**Comment by rolfik** [comment]
Currently I use VS 2022 to author Angular project.
It gives me only TS completions, but I have no Intellisense in Angular HTML templates and cannot easily switch to TS component file and back.
comparing it with Blazor support, it seems weak now.
Is this extension the only option to use Angular Intellisense in VS 2022 or did I miss something else?

**Comment by drzbida** [comment]
I see there's a pull request from almost two months ago regarding this issue. Any updates?

**Comment by Dylanwork** [comment]
Bump. I also am pretty much waiting for this.

**Comment by MariaSolOs** [comment]
Resolved now! The extension for VS2022 should now be [available in the marketplace](https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.AngularLanguageService2022) :) Thank you for your patience!
