### ISSUE TITLE
Unable to rename variables in VSCode due to Angular Language Service

### ISSUE THREAD

**Issue by JonKarta** [microsoft/vs-ng-language-service#36]
Whenever I try to rename a variable in VSCode, I receive a little tooltip and I am unable to rename that variable.

## Expected Behavior

I should be able to rename the variable in all places that it is used.

## Current Behavior

When I try to rename a variable, tooltip appears explaining that renaming is delegated to Angular Language Service.

![image](https://user-images.githubusercontent.com/71728717/171969795-de12dbbf-d269-4219-98f6-22761e1937d6.png)

**Comment by MariaSolOs** [comment]
@JonKarta This repository contains the implementation for Visual Studio, not VS Code. Please create the issue in [their repo](https://github.com/angular/vscode-ng-language-service).
