### ISSUE TITLE
Issue inside of a spec file with a host component

### ISSUE THREAD

**Issue by HoplaGeiss** [microsoft/vs-ng-language-service#57]
As you can see in the image bellow it tells me I have an unknown element.
This is not a problem with the rest of the code, the import are correct and the test works fine.
I have this issue everywhere in my application. It only happens in spec files.

![image](https://user-images.githubusercontent.com/5755785/205270294-084ffba2-4a9d-4d93-836c-3195f8ffc5ea.png)

**Comment by MariaSolOs** [comment]
The picture shows that you're using the VS Code extension. This is the one for Visual Studio. Please open the issue in https://github.com/angular/vscode-ng-language-service.
