### ISSUE TITLE
Items in Find All References window do not respond to double clicks

### ISSUE THREAD

**Issue by transmogrifix** [microsoft/vs-ng-language-service#60]
I am using VS 2022 v17.3.0, extension v1.1.4.

The extension correctly populates the Find All References window with references from ts and html files.
![image](https://user-images.githubusercontent.com/25490028/207917956-db54a49b-d5dd-41ba-861c-042faa117314.png)
The issue is that when I double click any row in the window nothing happens (I would expect that the file should be opened in the editor on that line/col).

When I disable the extension, not all references are found but the double click action works.
![image](https://user-images.githubusercontent.com/25490028/207918191-792b9117-605e-4f8c-b10c-e493b0788a83.png)

You can use my test project to reproduce.
* Clone https://github.com/transmogrifix/angular-app
* Open as folder in VS
* Open src/app/app.component.ts
* Right click on `title` and press Find All References 
* Try to double click on any found reference and nothing happens

**Comment by MariaSolOs** [comment]
@transmogrifix Thanks for reporting the issue!

Could you please check if the problem can be reproduced when opening the project as a solution in VS, instead of as a folder?

**Comment by transmogrifix** [comment]
Hi @MariaSolOs,
I tried using both "ASP.NET Core with Angular" and "Standalone TypeScript Angular project" template projects, behavior is the same - double click action is not working.
